import { describe, expectTypeOf, it } from 'vitest';
import type { GatewayChannelData, ScheduleData } from '../types/index.js';
import type { AgorClient, ClientInput, GatewayChannelsService, SchedulesService } from './index.js';

type ScheduleCreateInput = Parameters<SchedulesService['create']>[0];
type GatewayCreateInput = Parameters<GatewayChannelsService['create']>[0];
type SchedulePatchInput = Parameters<SchedulesService['patch']>[1];
type GatewayPatchInput = Parameters<GatewayChannelsService['patch']>[1];

function assertClientWriteBoundaries(client: AgorClient): void {
  void client.service('schedules').create({
    agentic_tool_config: { agentic_tool: 'codex' },
  });
  void client.service('gateway-channels').create({
    agentic_config: { agent: 'cursor' },
  });

  // Persisted removed tools and runtime-owned output fields are read-only.
  void client.service('schedules').create({
    // @ts-expect-error claude-code-cli is preserved only on stored Schedule rows.
    agentic_tool_config: { agentic_tool: 'claude-code-cli' },
  });
  void client.service('schedules').create({
    // @ts-expect-error created_at is owned by the schedule runtime.
    created_at: '2026-07-28T00:00:00.000Z',
  });
  void client.service('gateway-channels').create({
    // @ts-expect-error claude-code-cli is preserved only on stored GatewayChannel rows.
    agentic_config: { agent: 'claude-code-cli' },
  });
  void client.service('gateway-channels').create({
    // @ts-expect-error channel_key is generated by the gateway runtime.
    channel_key: 'caller-supplied-secret',
  });
}

void assertClientWriteBoundaries;

describe('public service write contracts', () => {
  it('derive client inputs from the active-only DTOs', () => {
    expectTypeOf<ScheduleCreateInput>().toEqualTypeOf<ClientInput<ScheduleData>>();
    expectTypeOf<GatewayCreateInput>().toEqualTypeOf<ClientInput<GatewayChannelData>>();
    expectTypeOf<SchedulePatchInput>().toEqualTypeOf<ClientInput<ScheduleData> | null>();
    expectTypeOf<GatewayPatchInput>().toEqualTypeOf<ClientInput<GatewayChannelData> | null>();
  });
});
