import { describe, expectTypeOf, it } from 'vitest';
import type {
  GatewayChannelCreateData,
  GatewayChannelPatchData,
  ScheduleCreateData,
  SchedulePatchData,
} from '../types/index.js';
import { MessageRole } from '../types/index.js';
import type { AgorClient, ClientInput, GatewayChannelsService, SchedulesService } from './index.js';

type ScheduleCreateInput = Parameters<SchedulesService['create']>[0];
type GatewayCreateInput = Parameters<GatewayChannelsService['create']>[0];
type SchedulePatchInput = Parameters<SchedulesService['patch']>[1];
type GatewayPatchInput = Parameters<GatewayChannelsService['patch']>[1];
type ScheduleUpdateInput = Parameters<SchedulesService['update']>[1];
type GatewayUpdateInput = Parameters<GatewayChannelsService['update']>[1];

function assertClientWriteBoundaries(client: AgorClient): void {
  void client.service('schedules').create({
    branch_id: 'branch-id',
    name: 'Nightly',
    cron_expression: '0 0 * * *',
    timezone_mode: 'utc',
    prompt: 'Run',
    agentic_tool_config: { agentic_tool: 'codex' },
  });
  void client.service('gateway-channels').create({
    name: 'Engineering',
    channel_type: 'slack',
    target_branch_id: 'branch-id',
    config: {},
    agentic_config: { agent: 'cursor' },
  });

  // Persisted removed tools and runtime-owned output fields are read-only.
  void client.service('schedules').create({
    branch_id: 'branch-id',
    name: 'Nightly',
    cron_expression: '0 0 * * *',
    timezone_mode: 'utc',
    prompt: 'Run',
    // @ts-expect-error claude-code-cli is preserved only on stored Schedule rows.
    agentic_tool_config: { agentic_tool: 'claude-code-cli' },
  });
  void client.service('schedules').create({
    branch_id: 'branch-id',
    name: 'Nightly',
    cron_expression: '0 0 * * *',
    timezone_mode: 'utc',
    prompt: 'Run',
    agentic_tool_config: { agentic_tool: 'codex' },
    // @ts-expect-error created_at is owned by the schedule runtime.
    created_at: '2026-07-28T00:00:00.000Z',
  });
  void client.service('gateway-channels').create({
    name: 'Engineering',
    channel_type: 'slack',
    target_branch_id: 'branch-id',
    config: {},
    // @ts-expect-error claude-code-cli is preserved only on stored GatewayChannel rows.
    agentic_config: { agent: 'claude-code-cli' },
  });
  void client.service('gateway-channels').create({
    name: 'Engineering',
    channel_type: 'slack',
    target_branch_id: 'branch-id',
    config: {},
    // @ts-expect-error channel_key is generated by the gateway runtime.
    channel_key: 'caller-supplied-secret',
  });

  // @ts-expect-error required create fields cannot be omitted.
  void client.service('schedules').create({ agentic_tool_config: { agentic_tool: 'codex' } });
  // @ts-expect-error local schedule creates require an IANA timezone.
  void client.service('schedules').create({
    branch_id: 'branch-id',
    name: 'Nightly',
    cron_expression: '0 0 * * *',
    timezone_mode: 'local',
    prompt: 'Run',
    agentic_tool_config: { agentic_tool: 'codex' },
  });
  void client.service('schedules').patch('schedule-id', {
    // @ts-expect-error schedules cannot be reparented by patch.
    branch_id: 'other-branch',
  });
  // @ts-expect-error required create fields cannot be omitted.
  void client.service('gateway-channels').create({ agentic_config: { agent: 'codex' } });

  void client.service('messages/bulk').create([
    {
      session_id: 'session-id',
      task_id: 'task-id',
      role: MessageRole.USER,
      type: 'user',
      content: 'Imported transcript row',
    },
  ]);
  // @ts-expect-error public Message CRUD does not expose full replacement.
  void client.service('messages').update('message-id', {});
  // @ts-expect-error public Message patch always targets one exact Message.
  void client.service('messages').patch(null, { content_preview: 'bulk patch' });
  // @ts-expect-error bulk insertion is only available on /messages/bulk.
  void client.service('messages').createMany([]);
  // @ts-expect-error /messages/bulk is a narrow create-only endpoint.
  void client.service('messages/bulk').find();

  // Provenance is derived from the authenticated transport, not caller input.
  // @ts-expect-error messageSource is daemon-owned provenance.
  void client.sessions.prompt('session-id', 'Prompt', { messageSource: 'gateway' });
  // @ts-expect-error messageSource is daemon-owned provenance.
  void client.tasks.run('task-id', { messageSource: 'gateway' });
}

void assertClientWriteBoundaries;

describe('public service write contracts', () => {
  it('derive client inputs from the active-only DTOs', () => {
    expectTypeOf<ScheduleCreateInput>().toEqualTypeOf<ClientInput<ScheduleCreateData>>();
    expectTypeOf<GatewayCreateInput>().toEqualTypeOf<ClientInput<GatewayChannelCreateData>>();
    expectTypeOf<SchedulePatchInput>().toEqualTypeOf<ClientInput<SchedulePatchData> | null>();
    expectTypeOf<GatewayPatchInput>().toEqualTypeOf<ClientInput<GatewayChannelPatchData> | null>();
    expectTypeOf<ScheduleUpdateInput>().toEqualTypeOf<never>();
    expectTypeOf<GatewayUpdateInput>().toEqualTypeOf<never>();
  });
});
