import { join } from 'node:path';
import type { OpenCodeNativeStateLayout } from './native-state.js';
import type { OpenCodeInvocationConfig } from './opencode-tool.js';

/** Hosted configuration is generated by Agor, never merged with repository policy. */
export function assertHostedOpenCodeInvocationConfig(config: OpenCodeInvocationConfig): void {
  if (config.plugin !== undefined || config.provider !== undefined) {
    throw new Error('Hosted OpenCode does not support plugins or provider configuration overrides');
  }
  for (const server of Object.values(config.mcp)) {
    if (!server || typeof server !== 'object' || !('type' in server) || server.type !== 'remote') {
      throw new Error(
        'Hosted OpenCode supports only remote MCP servers; local commands are not allowed'
      );
    }
  }
}

/**
 * These discovery controls are verified against the pinned executable. XDG alone
 * does not exclude project configuration, $HOME/.opencode, or system policy.
 * Keep the real HOME for tools; the pinned discovery-home override affects only
 * OpenCode. Never inherit OPENCODE_* selectors from the task/user environment.
 */
export function hostedOpenCodeEnvironment(
  layout: OpenCodeNativeStateLayout,
  inherited: NodeJS.ProcessEnv
): NodeJS.ProcessEnv {
  const environment = Object.fromEntries(
    Object.entries(inherited).filter(([key]) => !key.startsWith('OPENCODE_'))
  );
  return {
    ...environment,
    XDG_DATA_HOME: layout.xdg.data,
    XDG_CONFIG_HOME: layout.xdg.config,
    XDG_CACHE_HOME: layout.xdg.cache,
    XDG_STATE_HOME: layout.xdg.state,
    OPENCODE_DB: layout.liveDbPath,
    OPENCODE_DISABLE_PROJECT_CONFIG: 'true',
    OPENCODE_PURE: 'true',
    OPENCODE_DISABLE_DEFAULT_PLUGINS: 'true',
    OPENCODE_DISABLE_AUTOUPDATE: 'true',
    OPENCODE_DISABLE_MODELS_FETCH: 'true',
    OPENCODE_TEST_HOME: layout.scratchRoot,
    OPENCODE_TEST_MANAGED_CONFIG_DIR: join(layout.xdg.config, 'managed'),
  };
}
