import { mkdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import type { OpenCodeNativeStateLayout } from './native-state.js';
import type { OpenCodeInvocationConfig } from './opencode-tool.js';

/** Hosted configuration is generated by Agor, never merged with repository policy. */
export function assertHostedOpenCodeInvocationConfig(config: OpenCodeInvocationConfig): void {
  if (config.plugin !== undefined || config.provider !== undefined) {
    throw new Error('Hosted OpenCode does not support plugins or provider configuration overrides');
  }
  for (const server of Object.values(config.mcp)) {
    if (!server || typeof server !== 'object' || !('type' in server) || server.type !== 'remote') {
      throw new Error('Hosted OpenCode supports only remote MCP servers');
    }
  }
}

/** All OpenCode roots on scratch; no project/home/system config or inherited OPENCODE_* selectors. */
export function hostedOpenCodeEnvironment(
  layout: OpenCodeNativeStateLayout,
  inherited: NodeJS.ProcessEnv
): NodeJS.ProcessEnv {
  return {
    ...Object.fromEntries(
      Object.entries(inherited).filter(([key]) => !key.startsWith('OPENCODE_'))
    ),
    XDG_DATA_HOME: layout.xdg.data,
    XDG_CONFIG_HOME: layout.xdg.config,
    XDG_CACHE_HOME: layout.xdg.cache,
    XDG_STATE_HOME: layout.xdg.state,
    // OpenCode's temp dir defaults to os.tmpdir(); keep it on bounded Job-local scratch.
    TMPDIR: layout.scratchRoot,
    OPENCODE_DB: layout.liveDbPath,
    OPENCODE_DISABLE_PROJECT_CONFIG: 'true',
    OPENCODE_PURE: 'true',
    OPENCODE_DISABLE_AUTOUPDATE: 'true',
    OPENCODE_DISABLE_MODELS_FETCH: 'true',
    OPENCODE_TEST_HOME: layout.scratchRoot,
    OPENCODE_TEST_MANAGED_CONFIG_DIR: join(layout.xdg.config, 'managed'),
  };
}

/** Write the selected provider key where OpenCode reads it, never into a process environment. */
export async function writeHostedOpenCodeAuth(
  layout: OpenCodeNativeStateLayout,
  authContent: string
): Promise<void> {
  const directory = join(layout.xdg.data, 'opencode');
  await mkdir(directory, { mode: 0o700 });
  await writeFile(join(directory, 'auth.json'), authContent, { mode: 0o600, flag: 'wx' });
}
