/**
 * Unix User Management Utilities
 *
 * Provides utilities for managing Unix users for Agor.
 * Users follow the naming convention: agor_<short-id> or custom unix_username.
 *
 * @see context/guides/rbac-and-unix-isolation.md
 */

import { formatShortId } from '../lib/ids.js';
import type { UserID, UUID } from '../types/index.js';

/**
 * Default home directory base for Agor users
 */
export const AGOR_HOME_BASE = '/home';

/**
 * Default shell for new Agor users
 */
export const AGOR_DEFAULT_SHELL = '/bin/bash';

/**
 * Agor worktrees directory name within user home
 */
export const AGOR_WORKTREES_DIR = 'agor/worktrees';

/**
 * Generate a default Unix username for an Agor user
 *
 * Format: agor_<short-id>
 * Example: agor_03b62447
 *
 * @param userId - Full user UUID
 * @returns Unix username (e.g., 'agor_03b62447')
 */
export function generateUnixUsername(userId: UserID): string {
  const shortId = formatShortId(userId as UUID);
  return `agor_${shortId}`;
}

/**
 * Parse user short ID from Unix username
 *
 * @param username - Unix username (e.g., 'agor_03b62447')
 * @returns Short user ID (8 chars) or null if not an auto-generated name
 */
export function parseUnixUsername(username: string): string | null {
  const match = username.match(/^agor_([0-9a-f]{8})$/);
  return match ? match[1] : null;
}

/**
 * Check if username follows Agor auto-generated format
 *
 * @param username - Username to validate
 * @returns true if matches agor_<8-hex-chars> format
 */
export function isAutoGeneratedUsername(username: string): boolean {
  return /^agor_[0-9a-f]{8}$/.test(username);
}

/**
 * Validate Unix username format
 *
 * Unix usernames must:
 * - Start with lowercase letter or underscore
 * - Contain only lowercase letters, digits, underscores, hyphens
 * - Be 1-32 characters long
 *
 * @param username - Username to validate
 * @returns true if valid Unix username
 */
export function isValidUnixUsername(username: string): boolean {
  return /^[a-z_][a-z0-9_-]{0,31}$/.test(username);
}

/**
 * Get home directory path for a Unix user
 *
 * @param username - Unix username
 * @param homeBase - Base directory for homes (default: /home)
 * @returns Full home directory path
 */
export function getUserHomeDir(username: string, homeBase: string = AGOR_HOME_BASE): string {
  return `${homeBase}/${username}`;
}

/**
 * Get Agor worktrees directory path for a user
 *
 * @param username - Unix username
 * @param homeBase - Base directory for homes (default: /home)
 * @returns Full path to ~/agor/worktrees
 */
export function getUserWorktreesDir(username: string, homeBase: string = AGOR_HOME_BASE): string {
  return `${homeBase}/${username}/${AGOR_WORKTREES_DIR}`;
}

/**
 * Unix user management commands (to be executed via sudo)
 *
 * These are shell command strings for privileged user operations.
 */
export const UnixUserCommands = {
  /**
   * Check if a Unix user exists
   *
   * @param username - Unix username
   * @returns Command string (exits 0 if exists, non-zero if not)
   */
  userExists: (username: string) => `id "${username}" > /dev/null 2>&1`,

  /**
   * Create a new Unix user with home directory
   *
   * @param username - Unix username to create
   * @param shell - Login shell (default: /bin/bash)
   * @param homeBase - Base directory for home (default: /home)
   * @returns Command string
   */
  createUser: (
    username: string,
    shell: string = AGOR_DEFAULT_SHELL,
    homeBase: string = AGOR_HOME_BASE
  ) => `useradd -m -d "${homeBase}/${username}" -s "${shell}" "${username}"`,

  /**
   * Create user with specific UID/GID
   *
   * @param username - Unix username
   * @param uid - User ID
   * @param gid - Group ID (optional, defaults to uid)
   * @param shell - Login shell
   * @param homeBase - Home directory base
   * @returns Command string
   */
  createUserWithId: (
    username: string,
    uid: number,
    gid?: number,
    shell: string = AGOR_DEFAULT_SHELL,
    homeBase: string = AGOR_HOME_BASE
  ) => {
    const gidArg = gid !== undefined ? `-g ${gid}` : '';
    return `useradd -m -d "${homeBase}/${username}" -s "${shell}" -u ${uid} ${gidArg} "${username}"`;
  },

  /**
   * Delete a Unix user (keeps home directory)
   *
   * @param username - Unix username to delete
   * @returns Command string
   */
  deleteUser: (username: string) => `userdel "${username}"`,

  /**
   * Delete a Unix user and their home directory
   *
   * @param username - Unix username to delete
   * @returns Command string
   */
  deleteUserWithHome: (username: string) => `userdel -r "${username}"`,

  /**
   * Lock a Unix user account (disable login)
   *
   * @param username - Unix username
   * @returns Command string
   */
  lockUser: (username: string) => `usermod -L "${username}"`,

  /**
   * Unlock a Unix user account
   *
   * @param username - Unix username
   * @returns Command string
   */
  unlockUser: (username: string) => `usermod -U "${username}"`,

  /**
   * Get user's UID
   *
   * @param username - Unix username
   * @returns Command string (outputs UID)
   */
  getUserUid: (username: string) => `id -u "${username}"`,

  /**
   * Get user's primary GID
   *
   * @param username - Unix username
   * @returns Command string (outputs GID)
   */
  getUserGid: (username: string) => `id -g "${username}"`,

  /**
   * Get all groups a user belongs to
   *
   * @param username - Unix username
   * @returns Command string (outputs space-separated group names)
   */
  getUserGroups: (username: string) => `id -nG "${username}"`,

  /**
   * Create directory with proper ownership
   *
   * @param path - Directory path to create
   * @param username - Owner username
   * @param group - Owner group (defaults to username)
   * @param mode - Permission mode (default: 755)
   * @returns Command string
   */
  createOwnedDirectory: (path: string, username: string, group?: string, mode: string = '755') => {
    const grp = group || username;
    return `mkdir -p "${path}" && chown "${username}:${grp}" "${path}" && chmod ${mode} "${path}"`;
  },

  /**
   * Setup Agor worktrees directory structure for a user
   *
   * Creates ~/agor/worktrees with proper ownership
   *
   * @param username - Unix username
   * @param homeBase - Home directory base
   * @returns Command string
   */
  setupWorktreesDir: (username: string, homeBase: string = AGOR_HOME_BASE) => {
    const worktreesDir = `${homeBase}/${username}/${AGOR_WORKTREES_DIR}`;
    return `mkdir -p "${worktreesDir}" && chown -R "${username}:${username}" "${homeBase}/${username}/agor"`;
  },
} as const;
