export default {
  index: 'Overview',
  'getting-started': 'Getting Started',
  'extended-install': 'Extended Installation',
  '--- Features': {
    type: 'separator',
    title: 'Features',
  },
  'features-overview': 'Features Overview',
  worktrees: 'Worktrees',
  sessions: 'Sessions & Trees',
  boards: 'Boards & Zones',
  assistants: 'Assistants',
  'internal-mcp': 'Agor MCP Server',
  'rich-chat-ux': 'Rich Chat UX',
  'multiplayer-social': 'Multiplayer & Social',
  'environment-configuration': 'Environments',
  scheduler: 'Scheduler',
  cards: 'Cards (Beta)',
  artifacts: 'Artifacts',
  'api-proxies': 'API Proxies (CORS bypass)',
  'message-gateway': 'Message Gateway',
  '--- Reference': {
    type: 'separator',
    title: 'Reference',
  },
  architecture: 'Architecture',
  'typescript-client': 'TypeScript Client',
  'sdk-comparison': 'SDK Comparison',
  '--- Development': {
    type: 'separator',
    title: 'Development',
  },
  development: 'Development Guide',
  '--- Deployment': {
    type: 'separator',
    title: 'Deployment',
  },
  'multiplayer-unix-isolation': 'Full Multiplayer Mode',
  'containerized-execution': 'Containerized Execution',
};
